import Head from "next/head";
import { FC, ReactNode } from "react";
import styled from "styled-components";

type Props = {
  title: string;
  children: ReactNode;
};

export const Template: FC<Props> = ({ title, children }) => {
  return (
    <div>
      <Head>
        <title>{title}</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>{children}</div>
      <StFooter>
        <img src="/images/skyticket.png" alt="logo" />
      </StFooter>
    </div>
  );
};

const StFooter = styled.footer`
  width: 100%;
  height: 40px;
  text-align: center;
  color: #fff;
  background-color: #4d4d4d;
  display: flex;
  justify-content: center;
  align-items: center;
`;
